"""Download the site's typefaces from Google Fonts and self-host them.

Run once. The woff2 files land in static/fonts/ and are committed, so the build
never depends on a font CDN and no visitor request ever leaves the site's domain.
"""

from __future__ import annotations

import re
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FONT_DIR = ROOT / "static" / "fonts"

# A modern UA is what makes the API serve woff2 rather than truetype.
UA = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
)

FAMILIES = {
    # Display. The SOFT and WONK axes are why this face was chosen: at weight 800
    # and poster size they give it the inked, slightly off-kilter quality the
    # design is built on.
    "fraunces": "Fraunces:opsz,wght,SOFT,WONK@9..144,300..900,0..100,0..1",
    # Everything else: body, labels, captions, buttons. A crisp grotesque against
    # heavy Fraunces is what keeps the pages from reading as traditional literary.
    "schibsted": "Schibsted+Grotesk:wght@400..800",
}

LATIN = "U+0000-00FF"


def fetch(url: str) -> bytes:
    request = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(request, timeout=60) as response:
        return response.read()


def main() -> int:
    FONT_DIR.mkdir(parents=True, exist_ok=True)
    blocks_out: list[str] = []

    for slug, spec in FAMILIES.items():
        css = fetch(f"https://fonts.googleapis.com/css2?family={spec}&display=swap").decode()
        blocks = re.findall(r"@font-face \{.*?\}", css, re.S)
        kept = 0
        for block in blocks:
            if LATIN not in block:
                continue  # latin subset only, the site has no other scripts
            url_match = re.search(r"url\((https://[^)]+\.woff2)\)", block)
            weight_match = re.search(r"font-weight: ([^;]+);", block)
            if not url_match or not weight_match:
                continue
            weight = weight_match.group(1).strip().replace(" ", "-")
            name = f"{slug}-{weight}.woff2"
            (FONT_DIR / name).write_bytes(fetch(url_match.group(1)))
            family = re.search(r"font-family: '([^']+)'", block).group(1)
            blocks_out.append(
                "@font-face {\n"
                f"  font-family: '{family}';\n"
                "  font-style: normal;\n"
                f"  font-weight: {weight_match.group(1).strip()};\n"
                "  font-display: swap;\n"
                f"  src: url('../fonts/{name}') format('woff2');\n"
                "}"
            )
            kept += 1
            print(f"  {name}  {(FONT_DIR / name).stat().st_size // 1024} KB")
        print(f"{slug}: {kept} face(s)")

    css_path = ROOT / "static" / "css" / "fonts.css"
    css_path.parent.mkdir(parents=True, exist_ok=True)
    header = "/* Generated by scripts/fonts.py. Do not edit by hand. */\n\n"
    css_path.write_text(header + "\n\n".join(blocks_out) + "\n", encoding="utf-8")
    print(f"Wrote {css_path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
